version: '3.9'

services:
  postgres:
    image: postgres:16
    restart: always
    container_name: rate_app_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: webDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  app:
    build: .
    container_name: rate_app
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/webDB
      DB_USERNAME: user
      DB_PASSWORD: password
    depends_on:
      - postgres

