version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: report_service_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: webDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  app:
    build: .
    container_name: report_service_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/webDB
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password